name: Lint title
on:
  pull_request:
    types: [opened, reopened, edited]
permissions:
  pull-requests: read
jobs:
  lint:
    name: Lint title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
